import { ChromaClient, OpenAIEmbeddingFunction } from "chromadb";

const client = new ChromaClient({
  path: "http://localhost:8000",
});

const main = async () => {
  // Create a collection
  const response = await client.createCollection({
    name: "data-test2",
  });
  console.log(response);
};

if (!process.env.OPENAI_API_KEY) {
  throw new Error("OPENAI_API_KEY is not set");
}

const embeddingFunction = new OpenAIEmbeddingFunction({
  openai_api_key: process.env.OPENAI_API_KEY,
  openai_model: "text-embedding-3-small",
});

const addData = async () => {
  const collection = await client.getCollection({
    name: "data-test2",
    embeddingFunction: embeddingFunction,
  });
  const result = await collection.add({
    ids: ["id0"],
    documents: ["This is my entry"],
    // embeddings are mandatory and should be generated by a model
    // embeddings: [[0.1, 0.2, 0.3]],
  });
  console.log(result);
};

// main();

addData();
