import { ChromaClient } from "chromadb";

const client = new ChromaClient({
  path: "http://localhost:8000",
});

const main = async () => {
  // Create a collection
  const response = await client.createCollection({
    name: "data-test",
  });
  console.log(response);
};

const addData = async () => {
  const collection = await client.getCollection({
    name: "data-test",
  });
  const result = await collection.add({
    ids: ["id0"],
    documents: ["This is my entry"],
    // embeddings are mandatory and should be generated by a model
    embeddings: [[0.1, 0.2, 0.3]],
  });
  console.log(result);
};

addData();

// main();
